### ISSUE TITLE
redis.exceptions.RedisError: ZADD requires an equal number of values and scores

### ISSUE THREAD

**Issue by mallamsripooja** [redis-developer/basic-redis-chat-app-demo-python#2]
Hi, 

I have started using REDIS recently for one of my applications development, I am stuck with this error from a long time, can someone please help me resolve this error?

I tried following other discussion threads online but none of them had any resolutions for this issue.

> Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/socketio/server.py", line 720, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python3.7/dist-packages/socketio/server.py", line 745, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/usr/local/lib/python3.7/dist-packages/flask_socketio/__init__.py", line 283, in _handler
    *args)
  File "/usr/local/lib/python3.7/dist-packages/flask_socketio/__init__.py", line 766, in _handle_event
    ret = handler(*args)
  File "/home/<path_to>/basic-redis-chat-app-demo-python/chat/socketio_signals.py", line 84, in io_on_message
    utils.redis_client.zadd(room_key, {message_string: int(message["date"])})
  File "/usr/local/lib/python3.7/dist-packages/redis/client.py", line 2315, in zadd
    raise RedisError("ZADD requires an equal number of "
redis.exceptions.RedisError: ZADD requires an equal number of values and scores

Awaiting a solution, thanks in advance!

**Comment by mallamsripooja** [comment]
Turns out that I was using an older version of Redis python package hence the above error, on upgrading the Redis package the error is now resolved.
